version: "3.9"

services:
  backend:
    build: ./backend
    container_name: emnist-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: emnist-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
